-- ========================================
-- 5S Voting System
-- ========================================

create table five_s_votes (
  id bigint generated by default as identity primary key,
  inspection_date date not null,
  department_id bigint references departments(id),
  voter_id text, -- Can be employee ID or session ID/IP to prevent double voting
  vote_category TEXT DEFAULT 'rank_1',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for performance when filtering by date
create index idx_five_s_votes_date on five_s_votes(inspection_date);

-- Disable RLS for simplicity as per existing pattern in five_s_schema.sql
alter table five_s_votes disable row level security;
