-- ========================================
-- 5S Inspection Scoring System
-- ========================================

-- ตาราง five_s_inspections (การตรวจ 5ส)
create table five_s_inspections (
  id bigint generated by default as identity primary key,
  department_id bigint references departments(id),
  inspector_name text not null,
  inspection_date date not null default current_date,
  score_improvement int not null check (score_improvement between 0 and 10),   -- การเปลี่ยนที่ดีขึ้น
  score_cleanliness int not null check (score_cleanliness between 0 and 10),   -- ความสะอาด
  score_innovation int not null check (score_innovation between 0 and 10),     -- ความท้าทายแปลกใหม่
  total_score int not null default 0,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ปิด RLS เพื่อให้ทุกคนอ่าน/เขียนได้
alter table five_s_inspections disable row level security;
