-- ========================================
-- Employee Health & Activity System (Supabase PostgreSQL)
-- ========================================

-- 1. Create Tables
-- Branches (สาขา)
create table branches (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Departments (แผนก)
create table departments (
  id bigint generated by default as identity primary key,
  name text not null,
  branch_id bigint references branches(id),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Positions (ตำแหน่ง)
create table positions (
  id bigint generated by default as identity primary key,
  name text not null,
  level text check (level in ('บริหาร', 'ปฏิบัติการ', 'ฝึกงาน')) default 'ปฏิบัติการ',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Employees (พนักงาน)
create table employees (
  id bigint generated by default as identity primary key,
  employee_code text unique not null,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  branch_id bigint references branches(id),
  department_id bigint references departments(id),
  position_id bigint references positions(id),
  photo_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Activities (กิจกรรม)
create table activities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  activity_date date not null,
  start_time time without time zone,
  end_time time without time zone,
  location text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Activity Attendance (การเข้าร่วมกิจกรรม)
create table activity_attendance (
  id bigint generated by default as identity primary key,
  activity_id bigint references activities(id),
  employee_id bigint references employees(id),
  check_in_time timestamp with time zone default timezone('utc'::text, now()) not null,
  check_in_method text default 'QR',
  unique(activity_id, employee_id)
);

-- Health Records (ข้อมูลสุขภาพ)
create table health_records (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees(id),
  blood_pressure_systolic int,
  blood_pressure_diastolic int,
  heart_rate int,
  blood_sugar numeric(5,2),
  weight numeric(5,2),
  height numeric(5,2),
  notes text,
  recorded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  recorded_by uuid references auth.users(id)
);

-- Profiles (Linking Supabase Auth to Roles)
create table public.profiles (
  id uuid references auth.users(id) primary key,
  role text default 'User' check (role in ('Admin', 'User')),
  employee_id bigint references employees(id)
);

-- 2. Enable Row Level Security (RLS)
alter table branches enable row level security;
alter table departments enable row level security;
alter table positions enable row level security;
alter table employees enable row level security;
alter table activities enable row level security;
alter table activity_attendance enable row level security;
alter table health_records enable row level security;
alter table profiles enable row level security;

-- 3. Create Policies (Simple Public Access for Demo - Secure later)
create policy "Public read access" on branches for select using (true);
create policy "Public read access" on departments for select using (true);
create policy "Public read access" on positions for select using (true);
create policy "Public read access" on employees for select using (true);
create policy "Public read access" on activities for select using (true);
create policy "Public read access" on activity_attendance for select using (true);
create policy "Public read access" on health_records for select using (true);
create policy "Public read access" on profiles for select using (true);

create policy "Authenticated insert" on activities for insert to authenticated with check (true);
create policy "Authenticated update" on activities for update to authenticated using (true);
create policy "Authenticated delete" on activities for delete to authenticated using (true);

-- 4. Create Trigger to create profile after Sign Up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'User');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. Insert Sample Data
insert into branches (name, address) values ('สำนักงานใหญ่', 'กรุงเทพฯ'), ('สาขาระยอง', 'ระยอง');
insert into departments (name, branch_id) values ('IT', 1), ('HR', 1), ('Production', 2);
insert into positions (name, level) values ('Manager', 'บริหาร'), ('Staff', 'ปฏิบัติการ');
